export const TASKS = [
    {
        id: "TASK-001",
        projectId: "PROJ-A",
        projectName: "Traffic Sign Detection",
        status: "TODO",
        priority: "HIGH",
        image: "traffic_01.jpg",
        lastUpdated: "2023-10-25T10:00:00Z",
        assignee: "Annotator A",
        rejectComment: null,
    },
    {
        id: "TASK-002",
        projectId: "PROJ-A",
        projectName: "Traffic Sign Detection",
        status: "IN_PROGRESS",
        priority: "MEDIUM",
        image: "traffic_02.jpg",
        lastUpdated: "2023-10-25T11:30:00Z",
        assignee: "Annotator A",
        rejectComment: null,
    },
    {
        id: "TASK-003",
        projectId: "PROJ-B",
        projectName: "Pedestrian Tracking",
        status: "REJECTED",
        priority: "HIGH",
        image: "pedestrian_05.jpg",
        lastUpdated: "2023-10-24T15:45:00Z",
        assignee: "Annotator A",
        rejectComment: "Bounding box for person is too loose. Please tighten.",
    },
    {
        id: "TASK-004",
        projectId: "PROJ-A",
        projectName: "Traffic Sign Detection",
        status: "SUBMITTED",
        priority: "LOW",
        image: "traffic_03.jpg",
        lastUpdated: "2023-10-26T09:15:00Z",
        assignee: "Annotator A",
        rejectComment: null,
    },
    {
        id: "TASK-005",
        projectId: "PROJ-C",
        projectName: "Lane Segmentation",
        status: "APPROVED",
        priority: "MEDIUM",
        image: "lane_01.jpg",
        lastUpdated: "2023-10-20T14:20:00Z",
        assignee: "Annotator A",
        rejectComment: null,
    },
];

export const PROJECTS = [
    { id: "PROJ-A", name: "Traffic Sign Detection", type: "Bounding Box" },
    { id: "PROJ-B", name: "Pedestrian Tracking", type: "Bounding Box" },
    { id: "PROJ-C", name: "Lane Segmentation", type: "Polygon" },
];
